-- Table: public.news_content

-- DROP TABLE IF EXISTS public.news_content;
CREATE TABLE IF NOT EXISTS public.news_content
(
    id SERIAL PRIMARY KEY,
    title character varying NOT NULL,
    text text,
    file_id character varying,
    file_type character varying,
    button_str text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    bot_name character varying(30),
    business_type character varying(30),
    content_id bigint
);

ALTER TABLE public.news_content
ADD COLUMN file_unique_id varchar(100),
ADD CONSTRAINT news_content_file_unique_id_key UNIQUE (file_unique_id);

ALTER TABLE public.news_content
  ALTER COLUMN title DROP NOT NULL;






-------

-- Table: public.news_send_queue

-- DROP TABLE IF EXISTS public.news_send_queue;
CREATE TABLE IF NOT EXISTS public.news_send_queue
(
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_ref_id integer NOT NULL,
    news_id integer NOT NULL,
    bot_id integer,
    state text NOT NULL DEFAULT 'pending',  -- 已取消 send_state 枚举
    retry_count integer NOT NULL DEFAULT 0,
    last_try_at timestamp without time zone,
    sent_at timestamp without time zone,
    fail_reason text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT news_send_queue_user_ref_id_news_id_key UNIQUE (user_ref_id, news_id),

    CONSTRAINT news_send_queue_news_id_fkey
      FOREIGN KEY (news_id) REFERENCES public.news_content (id)
      ON UPDATE NO ACTION ON DELETE CASCADE,

    CONSTRAINT news_send_queue_user_ref_id_fkey
      FOREIGN KEY (user_ref_id) REFERENCES public.news_user (id)
      ON UPDATE NO ACTION ON DELETE CASCADE
);

-- Index: idx_send_queue_state

-- DROP INDEX IF EXISTS public.idx_send_queue_state;

CREATE INDEX IF NOT EXISTS idx_send_queue_state
    ON public.news_send_queue USING btree
    (state ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: idx_send_queue_state_bot







CREATE TABLE IF NOT EXISTS public.news_user
(
    id integer NOT NULL ,
    user_id bigint NOT NULL,
    business_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_sent_at timestamp without time zone,
    expire_at timestamp without time zone,
    CONSTRAINT news_user_pkey PRIMARY KEY (id),
    CONSTRAINT news_user_user_id_business_type_key UNIQUE (user_id, business_type)
)

ALTER TABLE public.news_user
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.news_user
    OWNER to neondb_owner;